name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build, test and generate coverage report
        run: ./gradlew clean test jacocoTestReport --info

      - name: Debug Jacoco files
        run: |
          echo "Listing Jacoco test report folder:"
          ls -R build/reports/jacoco/test || echo "No such directory"

      - name: Mostrar contenido parcial del XML
        run: |
          head -n 50 build/reports/jacoco/test/jacocoTestReport.xml

      - name: Check test coverage ≥ 80%
        run: |
          sudo apt-get install -y libxml2-utils

          REPORT_FILE=build/reports/jacoco/test/jacocoTestReport.xml

          if [ ! -f "$REPORT_FILE" ]; then
            echo "❌ Coverage report not found at $REPORT_FILE"
            exit 1
          fi

          COVERED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" "$REPORT_FILE")
          MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" "$REPORT_FILE")

          TOTAL=$(echo "$COVERED + $MISSED" | bc)
          PERCENT=$(echo "scale=2; $COVERED * 100 / $TOTAL" | bc)

          echo "📊 Instruction coverage: $PERCENT%"

          if (( $(echo "$PERCENT < 80" | bc -l) )); then
            echo "❌ Test coverage is below 80%"
            exit 1
          else
            echo "✅ Test coverage is sufficient"
          fi

      - name: Ensure excluded classes are not in coverage report
        run: |
          if grep -E "(dto|model|mapper)" build/reports/jacoco/test/jacocoTestReport.xml; then
            echo "❌ Excluded classes still appear in coverage report"
            exit 1
          else
            echo "✅ Excluded classes are not present in the coverage report"
          fi